"""
List of NSE stock symbols for scanning
This is a subset - in production, fetch from a database or API
"""

NSE_SYMBOLS = [
    # Nifty 50
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "HINDUNILVR", "ICICIBANK", "KOTAKBANK", 
    "LT", "SBIN", "BHARTIARTL", "AXISBANK", "ITC", "BAJFINANCE", "ASIANPAINT", 
    "MARUTI", "HCLTECH", "TITAN", "NESTLEIND", "SUNPHARMA", "ULTRACEMCO",
    "WIPRO", "NTPC", "ONGC", "TATASTEEL", "POWERGRID", "M&M", "TECHM", "DIVISLAB",
    "BAJAJFINSV", "ADANIPORTS", "JSWSTEEL", "INDUSINDBK", "TATAMOTORS", "HINDALCO",
    "GRASIM", "DRREDDY", "COALINDIA", "CIPLA", "BRITANNIA", "EICHERMOT",
    "HEROMOTOCO", "UPL", "SHREECEM", "BAJAJ-AUTO", "APOLLOHOSP", "BPCL", "TATACONSUM",
    "SBILIFE", "HDFCLIFE", "IOC",
    
    # Additional popular stocks
    "ADANIENT", "ADANIGREEN", "ADANIPOWER", "TATAPOWER", "VEDL", "SAIL", "NMDC",
    "ZOMATO", "PAYTM", "NYKAA", "POLICYBZR", "DELHIVERY",
    "TATAMTRDVR", "IRCTC", "LTI", "LTTS", "TECHM", "MPHASIS", "COFORGE",
    "PNB", "BANKBARODA", "CANBK", "UNIONBANK", "INDHOTEL",
    "DLF", "GODREJPROP", "OBEROIRLTY", "PRESTIGE", "BRIGADE",
    "PVR", "PVRINOX", "RELAXO", "BATA", 
    "DABUR", "MARICO", "COLPAL", "GODREJCP", "EMAMILTD",
    "PIDILITIND", "BERGEPAINT", "AKZOINDIA", "KANSAINER",
    "GAIL", "PETRONET", "IGL", "MGL", "GUJGASLTD",
    "TORNTPHARM", "LUPIN", "BIOCON", "AUROPHARMA", "CADILAHC",
    "SIEMENS", "ABB", "HAVELLS", "VOLTAS", "BLUESTARCO",
    
    # Mid-cap stocks
    "LICHSGFIN", "RECLTD", "PFC", "IRFC", "HUDCO",
    "TRENT", "APLAPOLLO", "DIXON", "AMBER", "BATAINDIA",
    "CROMPTON", "POLYCAB", "KEI", "FINOLEX",
    "ASTRAL", "SUPREMEIND", "BALKRISIND", "CEAT", "MRF",
    "PAGEIND", "PERSISTENT", "ROUTE", "HAPPSTMNDS",
    "ZYDUSLIFE", "ABBOTINDIA", "ALKEM", "IPCA", "LALPATHLAB",
    "METROPOLIS", "THYROCARE", "RAINBOW", "APOLLOTYRE",
    "CUMMINSIND", "BOSCHLTD", "MOTHERSON", "EXIDEIND", "AMARARAJA",
    "SRF", "ATUL", "GNFC", "DEEPAKNTR", "NAVINFLUOR",
    "PNB", "IOB", "CENTRALBK", "MAHABANK", "VIJAYABANK"
]

# Total: 150+ symbols
SYMBOLS_COUNT = len(NSE_SYMBOLS)
